---
# tasks file for create_ssh_folder
- name: create folder
  file: 
    path: "/home/{{ item.name }}//.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items:
    - {name: adam, group: adam}
    - {name: bob, group: bob}
- name: create authorized_key file
  file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items:
    - {name: adam, group: adam}
    - {name: bob, group: bob}
