---
- hosts: servers
  become: yes
  roles:
    - update_upgrade
    - create_users_groups
    - create_ssh_folder
    - setup_ufw

- hosts: nginx_server
  become: yes
  roles:
    - copy_nginx_keys
    - ufw_set_nginx
    - install_nginx

- hosts: mysql_server
  become: yes
  roles:
    - copy_mysql_keys
    - ufw_set_mysql
    - install_mysql
